#!/bin/env sh

set -e

for pkg in pkg/*; do
    # shellcheck disable=SC1090
    . "$pkg"
done

for pkg in internal/*; do
    # shellcheck disable=SC1090
    . "$pkg"
done

main() {
    printf "Installing theme..."
    installtheme
    printf "Done\\n"

    printf "Installing icons..."
    installicons
    printf "Done\\n"

    printf "Installing fonts..."
    installfonts
    printf "Done\\n"

    printf "Installing panel..."
    changepanel resources/panel.xml resources/panel
    printf "Done\\n"

    printf "Installing wallpaper..."
    changewallpaper resources/wallpaper.jpg
    printf "Done\\n"

    printf "Installing cursors..."
    changecursor Adwaita
    printf "Done\\n"

    echo "All done!"
}

main "$@"
